/**
 * Role catalogue for setup: common job titles grouped by family, all lowercase, without seniority
 * prefixes (those live in SENIORITY, so "senior product manager" is "product manager" + "senior").
 * Titles are matched as whole words inside job titles, so keep them short and canonical.
 */
export type RoleFamily = {
  id: string;
  label: string;
  titles: string[];
  /** Titles that commonly sneak in when searching this family but are usually unwanted. */
  exclude: string[];
};

export const SENIORITY = [
  "senior",
  "sr",
  "lead",
  "principal",
  "staff",
  "head",
  "director",
  "senior director",
  "vp",
  "vice president",
  "svp",
  "chief",
  "group",
  "manager",
  "associate director",
  "executive",
];

/** Exclusions useful for almost any senior search. */
export const COMMON_EXCLUDES = ["intern", "internship", "junior", "graduate", "trainee", "apprentice", "entry level"];

export const ROLE_FAMILIES: RoleFamily[] = [
  {
    id: "product",
    label: "Product Management",
    titles: [
      "product manager",
      "product lead",
      "head of product",
      "director of product",
      "vp product",
      "vp of product",
      "chief product officer",
      "group product manager",
      "technical product manager",
      "platform product manager",
      "growth product manager",
      "ai product manager",
      "data product manager",
      "product owner",
      "product operations",
      "product strategy",
    ],
    exclude: ["product marketing", "product designer", "product support", "product specialist"],
  },
  {
    id: "engineering",
    label: "Software Engineering",
    titles: [
      "software engineer",
      "software developer",
      "backend engineer",
      "frontend engineer",
      "full stack engineer",
      "full stack developer",
      "mobile engineer",
      "ios engineer",
      "android engineer",
      "web developer",
      "blockchain engineer",
      "smart contract engineer",
      "embedded engineer",
      "game developer",
      "solutions architect",
      "software architect",
      "engineering manager",
      "head of engineering",
      "director of engineering",
      "vp engineering",
      "cto",
      "chief technology officer",
      "tech lead",
    ],
    exclude: ["support engineer", "sales engineer"],
  },
  {
    id: "data-ai",
    label: "Data & AI",
    titles: [
      "data scientist",
      "data analyst",
      "data engineer",
      "analytics engineer",
      "machine learning engineer",
      "ml engineer",
      "ai engineer",
      "applied scientist",
      "research scientist",
      "mlops engineer",
      "business intelligence",
      "bi analyst",
      "head of data",
      "director of data",
      "chief data officer",
      "data architect",
      "quantitative analyst",
      "prompt engineer",
    ],
    exclude: ["data entry"],
  },
  {
    id: "design",
    label: "Design & UX",
    titles: [
      "product designer",
      "ux designer",
      "ui designer",
      "ux researcher",
      "user researcher",
      "interaction designer",
      "visual designer",
      "brand designer",
      "content designer",
      "ux writer",
      "design lead",
      "design manager",
      "head of design",
      "design director",
      "service designer",
      "motion designer",
    ],
    exclude: ["interior designer", "fashion designer"],
  },
  {
    id: "devops",
    label: "DevOps, Cloud & SRE",
    titles: [
      "devops engineer",
      "site reliability engineer",
      "sre",
      "platform engineer",
      "cloud engineer",
      "cloud architect",
      "infrastructure engineer",
      "systems engineer",
      "network engineer",
      "database administrator",
      "release engineer",
      "head of infrastructure",
    ],
    exclude: [],
  },
  {
    id: "security",
    label: "Cybersecurity",
    titles: [
      "security engineer",
      "application security",
      "cloud security",
      "security analyst",
      "penetration tester",
      "security architect",
      "soc analyst",
      "threat intelligence",
      "incident response",
      "ciso",
      "chief information security officer",
      "head of security",
      "information security manager",
      "grc analyst",
    ],
    exclude: ["security guard", "security officer"],
  },
  {
    id: "it",
    label: "IT & Enterprise Systems",
    titles: [
      "it manager",
      "it support",
      "systems administrator",
      "it director",
      "cio",
      "chief information officer",
      "erp consultant",
      "sap consultant",
      "salesforce administrator",
      "salesforce developer",
      "crm manager",
      "business systems analyst",
      "it project manager",
    ],
    exclude: [],
  },
  {
    id: "qa",
    label: "Quality Assurance & Testing",
    titles: ["qa engineer", "quality assurance", "test engineer", "sdet", "automation engineer", "qa lead", "qa manager", "performance engineer"],
    exclude: [],
  },
  {
    id: "program",
    label: "Project & Program Management",
    titles: [
      "project manager",
      "program manager",
      "technical program manager",
      "delivery manager",
      "scrum master",
      "agile coach",
      "pmo",
      "portfolio manager",
      "transformation manager",
      "change manager",
      "implementation manager",
    ],
    exclude: [],
  },
  {
    id: "marketing",
    label: "Marketing",
    titles: [
      "marketing manager",
      "product marketing manager",
      "growth marketing",
      "performance marketing",
      "digital marketing",
      "content marketing",
      "brand manager",
      "lifecycle marketing",
      "crm marketing",
      "seo manager",
      "social media manager",
      "community manager",
      "marketing analyst",
      "demand generation",
      "field marketing",
      "head of marketing",
      "marketing director",
      "cmo",
      "chief marketing officer",
    ],
    exclude: ["marketing assistant", "marketing intern"],
  },
  {
    id: "growth",
    label: "Growth",
    titles: ["growth manager", "head of growth", "growth lead", "growth analyst", "user acquisition", "monetization manager", "retention manager"],
    exclude: [],
  },
  {
    id: "content",
    label: "Content & Communications",
    titles: [
      "content strategist",
      "copywriter",
      "content writer",
      "technical writer",
      "editor",
      "communications manager",
      "pr manager",
      "public relations",
      "corporate communications",
      "internal communications",
      "head of communications",
    ],
    exclude: [],
  },
  {
    id: "sales",
    label: "Sales",
    titles: [
      "account executive",
      "enterprise account executive",
      "sales manager",
      "sales director",
      "head of sales",
      "vp sales",
      "chief revenue officer",
      "cro",
      "business development representative",
      "sales development representative",
      "inside sales",
      "key account manager",
      "regional sales manager",
      "country manager",
      "sales engineer",
      "pre sales",
      "solutions consultant",
      "sales operations",
      "revenue operations",
    ],
    exclude: ["retail sales associate", "sales assistant", "telesales"],
  },
  {
    id: "bizdev",
    label: "Business Development & Partnerships",
    titles: [
      "business development manager",
      "business development",
      "partnerships manager",
      "head of partnerships",
      "strategic partnerships",
      "alliances manager",
      "channel manager",
      "ecosystem manager",
      "head of business development",
    ],
    exclude: [],
  },
  {
    id: "customer",
    label: "Customer Success & Support",
    titles: [
      "customer success manager",
      "head of customer success",
      "account manager",
      "customer experience",
      "customer support",
      "support manager",
      "technical account manager",
      "onboarding manager",
      "client services",
      "relationship manager",
    ],
    exclude: ["call center agent"],
  },
  {
    id: "operations",
    label: "Operations",
    titles: [
      "operations manager",
      "business operations",
      "head of operations",
      "director of operations",
      "coo",
      "chief operating officer",
      "operations analyst",
      "process excellence",
      "operational excellence",
      "general manager",
      "chief of staff",
    ],
    exclude: [],
  },
  {
    id: "strategy",
    label: "Strategy & Consulting",
    titles: [
      "strategy manager",
      "head of strategy",
      "corporate strategy",
      "corporate development",
      "management consultant",
      "strategy consultant",
      "business analyst",
      "innovation manager",
      "venture builder",
      "entrepreneur in residence",
      "special projects",
    ],
    exclude: [],
  },
  {
    id: "finance",
    label: "Finance & Accounting",
    titles: [
      "financial analyst",
      "fp&a",
      "finance manager",
      "finance director",
      "head of finance",
      "cfo",
      "chief financial officer",
      "controller",
      "financial controller",
      "accountant",
      "chartered accountant",
      "treasury manager",
      "tax manager",
      "internal auditor",
      "audit manager",
      "accounts payable",
      "payroll manager",
    ],
    exclude: ["accounts assistant", "bookkeeper"],
  },
  {
    id: "banking",
    label: "Banking & Payments",
    titles: [
      "relationship manager",
      "credit analyst",
      "credit risk",
      "corporate banking",
      "retail banking",
      "private banker",
      "wealth manager",
      "payments manager",
      "head of payments",
      "card product manager",
      "cash management",
      "trade finance",
      "branch manager",
    ],
    exclude: ["teller", "bank clerk"],
  },
  {
    id: "investments",
    label: "Investments, Trading & Crypto",
    titles: [
      "investment analyst",
      "investment manager",
      "investment banker",
      "associate investment banking",
      "portfolio manager",
      "fund manager",
      "venture capital",
      "private equity",
      "trader",
      "quantitative trader",
      "quant researcher",
      "market maker",
      "research analyst",
      "equity research",
      "asset management",
      "tokenization",
      "digital assets",
      "crypto analyst",
    ],
    exclude: [],
  },
  {
    id: "risk",
    label: "Risk & Compliance",
    titles: [
      "compliance manager",
      "compliance officer",
      "head of compliance",
      "chief compliance officer",
      "aml analyst",
      "kyc analyst",
      "mlro",
      "financial crime",
      "risk manager",
      "operational risk",
      "enterprise risk",
      "fraud analyst",
      "fraud manager",
      "regulatory affairs",
      "governance risk",
      "head of risk",
      "chief risk officer",
    ],
    exclude: [],
  },
  {
    id: "legal",
    label: "Legal",
    titles: [
      "legal counsel",
      "general counsel",
      "corporate counsel",
      "lawyer",
      "associate lawyer",
      "paralegal",
      "contracts manager",
      "head of legal",
      "privacy counsel",
      "data protection officer",
      "company secretary",
    ],
    exclude: [],
  },
  {
    id: "people",
    label: "HR & People",
    titles: [
      "hr manager",
      "hr business partner",
      "people partner",
      "head of people",
      "chief people officer",
      "chro",
      "people operations",
      "hr generalist",
      "compensation and benefits",
      "total rewards",
      "learning and development",
      "organizational development",
      "employee experience",
      "hr director",
    ],
    exclude: ["hr assistant"],
  },
  {
    id: "talent",
    label: "Recruiting & Talent",
    titles: ["recruiter", "technical recruiter", "talent acquisition", "talent partner", "head of talent", "sourcer", "recruitment manager", "employer branding"],
    exclude: [],
  },
  {
    id: "supply",
    label: "Supply Chain & Logistics",
    titles: [
      "supply chain manager",
      "logistics manager",
      "procurement manager",
      "category manager",
      "buyer",
      "sourcing manager",
      "warehouse manager",
      "fleet manager",
      "demand planner",
      "inventory manager",
      "head of supply chain",
    ],
    exclude: ["warehouse associate", "picker", "driver"],
  },
  {
    id: "engineering-other",
    label: "Engineering (non-software)",
    titles: [
      "mechanical engineer",
      "electrical engineer",
      "civil engineer",
      "chemical engineer",
      "structural engineer",
      "process engineer",
      "manufacturing engineer",
      "hardware engineer",
      "petroleum engineer",
      "energy engineer",
      "sustainability manager",
      "hse manager",
    ],
    exclude: [],
  },
  {
    id: "healthcare",
    label: "Healthcare & Life Sciences",
    titles: [
      "physician",
      "nurse",
      "pharmacist",
      "clinical research",
      "clinical operations",
      "medical affairs",
      "medical science liaison",
      "healthcare administrator",
      "biostatistician",
      "regulatory affairs specialist",
      "health informatics",
    ],
    exclude: [],
  },
  {
    id: "research",
    label: "Research & Science",
    titles: ["research scientist", "research engineer", "economist", "policy analyst", "lab manager", "scientist", "researcher"],
    exclude: [],
  },
  {
    id: "education",
    label: "Education",
    titles: ["teacher", "lecturer", "professor", "instructional designer", "curriculum developer", "education manager", "academic director", "tutor"],
    exclude: [],
  },
  {
    id: "real-estate",
    label: "Real Estate & Construction",
    titles: ["property manager", "real estate agent", "leasing manager", "asset manager", "facilities manager", "construction manager", "quantity surveyor", "architect", "development manager"],
    exclude: [],
  },
  {
    id: "hospitality",
    label: "Hospitality, Travel & Retail",
    titles: ["hotel manager", "front office manager", "revenue manager", "restaurant manager", "store manager", "retail manager", "visual merchandiser", "e commerce manager", "travel consultant"],
    exclude: [],
  },
  {
    id: "executive",
    label: "Executive & Leadership",
    titles: ["ceo", "chief executive officer", "managing director", "general manager", "country manager", "founder", "co founder", "president", "chief of staff", "board member", "non executive director"],
    exclude: [],
  },
  {
    id: "admin",
    label: "Administrative & Office",
    titles: ["executive assistant", "personal assistant", "office manager", "administrative assistant", "receptionist", "coordinator"],
    exclude: [],
  },
];

/** Every title once, with the families it belongs to (a title can sit in several). */
export function allTitles(): { title: string; families: string[] }[] {
  const map = new Map<string, string[]>();
  for (const f of ROLE_FAMILIES) {
    for (const t of f.titles) map.set(t, [...(map.get(t) ?? []), f.label]);
  }
  return [...map].map(([title, families]) => ({ title, families })).sort((a, b) => a.title.localeCompare(b.title));
}
